# Generated by Django 3.1.2 on 2020-10-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetailMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('director', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.movie')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='movies.planet')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='movies.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.movie')),
            ],
        ),
    ]
