# Generated by Django 3.1.2 on 2020-10-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201002_0533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailMovie',
            new_name='MovieDetail',
        ),
    ]
